--Users Table
CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_uid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    email VARCHAR(200) NOT NULL UNIQUE,
    user_name VARCHAR(100) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    modified_at TIMESTAMP WITH TIME ZONE
);
